#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a com.brave.Browser desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs desktop='^5'

#Wallpaper
nitrogen --restore &

# Cursor
xsetroot -cursor_name left_ptr &

# Notifications
/usr/bin/dunst &

# Network Applet
nm-applet --indicator &
